baseURL = 'https://akfoundationindia.com/'
languageCode = 'en-us'
title = 'AK Foundation - Reg. No: 945/2010 | Empowering Lives Through Sports & Annadhanam'
theme = 'NGO-website'
[params]
favicon = '/favicon.jpg'
description = 'AK Foundation empowers rural sports talent, supports the underprivileged through Annadhanam, and fosters environmental stewardship, moral education, and care for the voiceless. Join us to create lasting impact through our initiatives and programs.'
keywords = 'AK Foundation, Rural Talent Development, Environmental Stewardship, Voiceless Support, Moral Science Education, Sports Academy, Educational Academy, Community Services, Tamil Nadu NGOs, Annadhanam, Food Offerings, Animal Welfare, Animal Care, Child Abuse Awareness, Drug Abuse Awareness, PoCSO, PoSH, Anti-Corruption Training, Social Work, Social Service, Community Outreach, Youth Development, Career Guidance, Sustainable Living, Tree Plantation Drives, Rainwater Harvesting, Waste Management, Adoption Drives, Family Counseling, Marriage Support, Rural Education, NGO Initiatives, Humanitarian Aid, Charity in Tamil Nadu, Nonprofit Organization, Volunteering Opportunities, Social Justice, Community Building.'
author = 'Balachandiran - TenSketch'
logo = '/images/logo/Success-Solutions-logo-2.jpeg'
og_image = '/ogimage.jpg'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[asset]
  # Enable Hugo pipes for SCSS
  enable = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About Us"
    url = "/about-us"
    weight = 2
  [[menu.main]]
    name = "AK Schools"
    url = "/ak-schools"
    weight = 3
    [[menu.main]]
      parent = "AK Schools"
      name = "AK School of Sports"
      url = "/ak-school-of-sports"
      weight = 1
    [[menu.main]]
      parent = "AK Schools"
      name = "AK School of Education"
      url = "/ak-school-of-education"
      weight = 2
    [[menu.main]]
      parent = "AK Schools"
      name = "AK School of Voiceless"
      url = "/ak-school-of-voiceless"
      weight = 3
    [[menu.main]]
      parent = "AK Schools"
      name = "AK School of Environment"
      url = "/ak-school-of-environment"
      weight = 4
    [[menu.main]]
      parent = "AK Schools"
      name = "AK School of Moral Science"
      url = "/ak-school-of-moral-science-and-anti-corruption"
      weight = 5
  [[menu.main]]
    name = "Services"
    url = "/services"
    weight = 3
  [[menu.main]]
    name = "Activities"
    url = "/activities"
    weight = 4
  [[menu.main]]
    name = "Gallery"
    weight = 5
    [[menu.main]]
      parent = "Gallery"
      name = "Photo Gallery"
      url = "/photo-gallery"
      weight = 1
    [[menu.main]]
      parent = "Gallery"
      name = "Video Gallery"
      url = "/video-gallery"
      weight = 2
      
  [[menu.main]]
    name = "Contact Us"
    url = "#contact-us"
    weight = 6

  [[menu.footer]]    
    name = "Join Us"
    url = "/join-us"
    weight = 1
  [[menu.footer]]
    name = "Terms & Conditions"
    url = "/terms-and-conditions"
    weight = 2
